### ISSUE TITLE
Remove your personals items

### ISSUE THREAD

**Issue by BBavouzet** [drmikecrowe/linux-bootstrap#1]
Hello,

First, sorry for my poor English.
I find your repository on the awesome dev.to site ;-)

How can I remove yours items ? I tried to remove a task (awscli.sh) created by `stub.sh` but, after build the task is always in `bootstrap-1.0.0.sh`.
So, it's an idea for you to add a remove item feature ?
I have made a script too, for configure fresh Linux install but, it's a poor script.

Thanks for you repository and your share,
And thank you for your response,

Regards,

Benoît

**Comment by drmikecrowe** [comment]
Thanks for asking, that's a good idea.  [Added instructions](https://github.com/drmikecrowe/linux-bootstrap#adapting-to-your-needs)
