### ISSUE TITLE
target directories and build.sh into blank branch  

### ISSUE THREAD

**Issue by BBavouzet** [drmikecrowe/linux-bootstrap#2]
Hello and sorry,

In your `blank` branch, there are no `./target` dir and `bootstrap-1.0.0.sh` file. And, `./build.sh`return an error.
I have added my items with `stub.sh` scripts. I added tests and install commands for each. And run `build.sh`.
I don't see where I make mistake.

Thanks for your help,

Regards,

Benoît B

**Comment by drmikecrowe** [comment]
Create the target directory and run build again. It creates your
bootstrap.sh file

**Comment by BBavouzet** [comment]
I have the same error message in french : `sed: impossible de lire ./target/bootstrap-*.sh: Aucun fichier ou dossier de ce type`. This mean in English `sed: impossible readind ./target/bootstrap-*.sh: no file or directories of this type`.

**Comment by BBavouzet** [comment]
Ok, there is a error to the install url of Bashing on their readme.
Now I have these messages :
```
Creating /home/benoit/Documents/projects/myProjects/Scripts Bash/linux-bootstrap/target/bootstrap-0.0.1-SNAPSHOT.sh ...
/home/benoit/.bin/bashing: ligne 533 : cd: trop d'arguments
(ERROR) Cannot write to given Output File: /bootstrap-0.0.1-SNAPSHOT.sh.
(ERROR) An error occured while running task 'compile'.
sed: impossible de lire ./target/bootstrap-*.sh: Aucun fichier ou dossier de ce type
```

**Comment by drmikecrowe** [comment]
If you want to pull my blank branch, it now has `target`.

However, I simply did:

```
mkdir target
./build.sh
```

and `target/bootstrap-0.0.1-SNAPSHOT.sh` was created.

NOTE:  You control your version number in `bashing.project` in the root directory

**Comment by BBavouzet** [comment]
Hello,

**Found !**
It's only I have one space in a folder name in the path of my project...
All works fine now.

For information :
- I use your script for the host,
- the host is a fresh install of Pop!-os 19.10,
- whith, `GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)`.

Thanks a lot for your fast responses !
And, for your script.

See you on dev.to ! :-)

Best regards,

Benoît
